# Generated by Django 4.2.25 on 2025-10-27 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("part", "0142_remove_part_last_stocktake_remove_partstocktake_note_and_more"),
        ("company", "0075_company_tax_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="HarmonizedSystemCode",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Harmonized System Code",
                        max_length=20,
                        verbose_name="Code",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        help_text="Description of the Harmonized System Code",
                        max_length=250,
                        verbose_name="Description",
                    ),
                ),
                (
                    "notes",
                    models.CharField(
                        blank=True,
                        help_text="Additional notes about the HS code",
                        max_length=500,
                        verbose_name="Notes",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        help_text="Part category associated with this HS code",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hs_codes",
                        to="part.partcategory",
                        verbose_name="Category",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        help_text="Customer associated with this HS code",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hs_codes",
                        to="company.company",
                        verbose_name="Customer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Harmonized System Code",
                "verbose_name_plural": "Harmonized System Codes",
            },
        ),
    ]
